### ISSUE TITLE
Is there a list for the projects under support from Open Wallet Foundation?

### ISSUE THREAD

**Issue by johnnynanjiang** [openwallet-foundation/project-proposals#25]
Or s there a wallet project ongoing aiming to fulfil the use case document at 
https://github.com/openwallet-foundation/architecture-sig/blob/main/docs/use-cases/use-cases.md

**Comment by tkuhrt** [comment]
You can see the project proposals that have been accepted in https://github.com/openwallet-foundation/project-proposals/tree/main/projects. We are also capturing this information [here](https://tac.openwallet.foundation/projects/) (although it has not yet been updated for the latest accepted projects -- see https://github.com/openwallet-foundation/tac/pull/75). You can also see additional proposed projects at https://github.com/openwallet-foundation/project-proposals/pulls.

**Comment by johnnynanjiang** [comment]
Thanks @tkuhrt for the prompt response.

Just another question, apart from the proposals, is there a list for the ongoing projects which have been accepted and are under active development under Open Wallet Foundation?

**Comment by tkuhrt** [comment]
Yes.

> We are also capturing this information [here](https://tac.openwallet.foundation/projects/) (although it has not yet been updated for the latest accepted projects -- see https://github.com/openwallet-foundation/tac/pull/75).

**Comment by tkuhrt** [comment]
BTW, since all of the projects that have been accepted are in the Labs stage, you can find the source for the projects at https://github.com/openwallet-foundation-labs (at least the ones that have been transferred so far).

**Comment by johnnynanjiang** [comment]
Thanks @tkuhrt , got it at https://tac.openwallet.foundation/projects/

**Comment by johnnynanjiang** [comment]
Hi @tkuhrt ,

As I saw, the listed projects are mainly implementations of specifications, frameworks and components.

Just wonder if there is a standalone, working as a whole wallet project, that incorporates OpenWallet's specs and standards?

If I'm not wrong, the goal of OpenWallet Foundation is to provide "open, secure and interoperable digital wallet solutions", so I assume the final product would be a digital wallet built on OpenWallet Foundations specs / solutions / components, is taht correct?

Thanks and regards,
Johnny

**Comment by tkuhrt** [comment]
Hi, @johnnynanjiang. Most of what we have currently are components that others can use to build their wallet solutions. It has been mentioned in the past that we do not expect to have an OpenWallet Foundation wallet. Obviously, things could change in the future, but currently that is the thought. Also, OpenWallet Foundation will use specifications and standards create by standards development organizations. There is no expectation that OWF will create specifications/standards. Hope this helps.

**Comment by jorgefl0** [comment]
This list may be a good start: https://tac.openwallet.foundation/projects/#active-projects

The Agent Framework JavaScript OSS project recently accepted into the Growth stage is currently the most mature "production" grade Wallet engine under the OWF.

**Comment by johnnynanjiang** [comment]
Thanks @jorgefl0 and @tkuhrt.

My understanding based on the information you kindly provided, is that the projects would get tractions and usage at `growth` and `impact` stages, where they could use adopters.md to gather adoption information.

It sounds a good plan and reasonable, thanks.
