### ISSUE TITLE
correct way

### ISSUE THREAD

**Issue by ghost** [openwallet-foundation/project-proposals#31]

**Comment by tkuhrt** [comment]
Hi, @lucasnuic : Are you looking to propose a project to the OpenWallet Foundation? If so, please follow the [instructions for proposing a project](https://github.com/openwallet-foundation/project-proposals?tab=readme-ov-file#instructions-for-proposing-a-project). You can also see more about the [OpenWallet Foundation's Project Lifecycle on the Technical Advisory Council website](https://tac.openwallet.foundation/governance/project-lifecycle/).
